config/routes.rb
Rails.application.routes.draw do
  get 'appointment/:id', to: 'appointment#show', as: 'appointment_show'
  post 'appointment/create'
  get 'coaches', to: 'coach#index'
  get 'coach/:id', to: 'coach#show', as: 'coach_show'
  get 'student/new'
  get 'student/logout'
  post 'student/create'

  
  root to: 'home#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
# frozen_string_literal: true

class Appointment < ApplicationRecord
end

app/models/availability.rb
# frozen_string_literal: true

class Availability < ApplicationRecord
  belongs_to :user
  has_many :slots

  DAYS_OF_WEEK = %w[Sunday Monday Tuesday Wednesday Thursday Friday Saturday].freeze
end

app/models/coach.rb
# frozen_string_literal: true

class Coach < User
end

app/models/slot.rb
# frozen_string_literal: true

# Coaching Availabilities
# represented as starting time slots
class Slot < ApplicationRecord
  belongs_to :availability

  using Refinements
  DURATION_IN_MINUTES = 30

  def generate_time_slots(start_time:, finish_time:)
    start_time.remove_all_spaces! # TODO: move this to the importer
    finish_time.remove_all_spaces! # TODO: move this to the importer
    validate_duration_in_minutes
    validate_times(start_time, finish_time)
    compile_and_return_time_slots(Time.parse(start_time), Time.parse(finish_time))
  end

  class << self
    # N + 1 fix
    def all_with_availabilities(ids)
      includes(:availability).where('availability_id IN (?)', ids).references(:availability)
    end
  end

  private

  def validate_duration_in_minutes
    error_message = "DURATION_IN_MINUTES '#{DURATION_IN_MINUTES}' failed validation."
    raise ArgumentError, error_message unless [15, 30, 60].include? DURATION_IN_MINUTES
  end

  def validate_times(*times)
    times.each do |time|
      raise(ArgumentError, "Time '#{time}' failed validation.") unless regex_match_by_time_format(time)
    end
  end

  def regex_match_by_time_format(time)
    time.match(/^[0-9]{1,2}\:[0-9]{2}?[AP][M]/i)
  end

  # FIXME: Fix 'start_time' bug...
  #
  # ...when start_time is on the half hour (9:30AM),
  # we incorrectly get 1 extra time slot.
  #
  # Formula:
  #
  #   (finish_time - start_time) * (60 / DURATION_IN_MINUTES)
  #
  # Examples:
  #
  #   => start time = 9:00
  #   => finish time = 15:00
  #   => DURATION_IN_MINUTES = 30
  #
  #   60 / 30 = 2 (half hour)
  #   (15 - 9) * 2 = 12 time slots
  #
  #   Doubling the number of iterations, giving us the ability to
  #   fill time slots for every 30 minutes.
  #
  #   => DURATION_IN_MINUTES = 15
  #
  #   60 / 15 = 4 (quarter hour)
  #   (15 - 9) * 4 = 24 time slots
  #
  #   Quadrupling the number of iterations, giving us the ability
  #   to fill time slots for every 15 minutes.
  #
  def compile_and_return_time_slots(start, finish)
    slots = []
    total = num_slots(start, finish)
    1.upto(total) do
      slots << start.to_formatted_string
      start += (DURATION_IN_MINUTES * 60)
    end
    slots
  end

  def num_slots(start, finish)
    (finish.hour - start.hour) * (60 / DURATION_IN_MINUTES)
  end
end

app/models/student.rb
# frozen_string_literal: true

class Student < User
  using Refinements
  validates :name, presence: true

  def to_coaches_time_zone(time:, coach:)
    coaches_time_zone = "#{time} #{coach.parse_time_zone}"
    coaches_time_zone.in_time_zone(parse_time_zone).no_dst
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :availabilities

  # TODO: Think about storing this with it pre-parsed
  # To successfully work with String '.in_time_zone'
  def parse_time_zone
    time_zone.gsub(/\(GMT.*?\)\s/, '')
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/appointment_controller.rb
# frozen_string_literal: true

class AppointmentController < ApplicationController
  def show; end

  def create
    slot = Slot.find(appointment_params[:slot_id])
    appointment = Appointment.new(slot_id: slot.id, coach_id: slot.availability.user.id,
                                  student_id: session[:student_id])

    if appointment.save
      slot.update_attributes(available: false)
      redirect_to action: :show, id: appointment.id
    else
      render controller: :coach, action: :show, id: slot.availability.user.id
    end
  end

  private

  def appointment_params
    params.permit(:slot_id)
  end
end

app/controllers/coach_controller.rb
# frozen_string_literal: true

class CoachController < ApplicationController
  def index
    @coaches = Coach.all # TODO: Skip fully booked coaches!
  end

  def show
    @coach = Coach.includes(:availabilities).find(params[:id])
    @student = Student.find(session[:student_id])
    @slots = Slot.all_with_availabilities(@coach.availabilities.ids)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @student_id = session[:student_id]
  end
end

app/controllers/student_controller.rb
# frozen_string_literal: true

class StudentController < ApplicationController
  before_action :setup_student, :setup_time_zones, only: [:new]

  def new; end

  def create
    student = Student.new(name: student_params[:name], time_zone: student_params[:time_zone])
    if student.save
      session[:student_id] = student.id
      redirect_to coaches_path
    else
      @student = student
      setup_time_zones
      render action: :new
    end
  end

  def logout
    session[:student_id] = nil
    redirect_to root_path
  end

  private

  def student_params
    params.require(:student).permit(:name, :time_zone)
  end

  def setup_student
    @student = Student.new
  end

  def setup_time_zones
    @time_zones = ActiveSupport::TimeZone.us_zones
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/coach_helper.rb
# frozen_string_literal: true

module CoachHelper
  def time_format(date_time)
    date_time.strftime('%l:%M %p').strip
  end

  def appointment_confirmation(slot, time, duration)
    "#{Availability::DAYS_OF_WEEK[slot.availability.day_of_week]} at #{time} for #{duration} minutes."
  end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
  def get_route(student_id)
    if student_id
      coaches_path
    else
      student_new_path
    end
  end
end

app/views/appointment/_form.html.erb
<%= form_with url: appointment_create_path, local: true do |form| %>
  <%= form.hidden_field :slot_id, id: 'slot-id' %>
  <div class="form-group">
    <label for="coach-name">Coach:</label>
    <%= form.text_field :coach_name, id: 'coach-name', class: 'form-control', disabled: true %>
  </div>
  <div class="form-group">
    <label for="slot-time">Appointment:</label>
    <%= form.text_field :appointment, id: 'appointment', class: 'form-control', disabled: true %>
  </div>
  <div class="form-group">
    <%= form.submit 'Book Appointment', class: "btn btn-md btn-primary btn-block" %>
  </div>
<% end %>

app/views/appointment/_modal.html.erb
<div class="modal fade" id="confirmAppointmentModal" tabindex="-1" role="dialog" aria-labelledby="confirmAppointmentModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="confirmAppointmentModalLabel">Confirm</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render partial: 'appointment/form' %>
      </div>
    </div>
  </div>
</div>

<%= content_for(:javascript) do %>
  <script>
      $('#confirmAppointmentModal').on('show.bs.modal', function (event) {
          var button = $(event.relatedTarget);
          var appointment = button.data('appointment')
          var coachName = button.data('coach-name');
          var slotId = button.data('slot-id');
          var modal = $(this);
          modal.find('.modal-body #appointment').val(appointment);
          modal.find('.modal-body #coach-name').val(coachName);
          modal.find('.modal-body #slot-id').val(slotId);
      })
  </script>
<% end %>

app/views/appointment/create.html.erb
<h1>Appointment#create</h1>
<p>Find me in app/views/appointment/create.html.erb</p>

app/views/appointment/show.html.erb
<h1 class="h2 text-center">Appointment Booked!</h1>
<div class="text-center pt-4">
  <p class="text-center">You'll be hearing from your Coach soon.</p>
</div>

app/views/coach/index.html.erb
<h1 class="h2 text-center">Available Coaches</h1>
<div class="text-center3 pt-4">
  <div class="row">
    <div class="col-6 offset-3 text-center">
      <% @coaches.each do |coach| %>
        <div class="p-1"><%= link_to coach.name, coach_show_path(coach.id), class: 'coach' %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/coach/show.html.erb
<p class="text-secondary text-center pb-0 mb-0">
  <small>COACH</small>
</p>
<h1 class="h2 pt-0 mb-0 text-center"><%= @coach.name %></h1>
<h2 class="h4 text-center text-secondary pt-3"><%= Slot::DURATION_IN_MINUTES %> Minute Time Slots</h2>
<div class="pt-3">

  <div class="table-responsive">
    <table class="table">
      <thead>
      <tr>
        <% Availability::DAYS_OF_WEEK.each do |day| %>
          <th scope="col"><%= day %></th>
        <% end %>
      </tr>
      </thead>
      <tbody>
      <tr>
        <% Availability::DAYS_OF_WEEK.each_with_index do |_day, index| %>
          <td>

            <% @slots.each do |slot| %>
              <% if slot.availability.day_of_week == index %>
                <div class="p-1">
                  <% time = time_format(@student.to_coaches_time_zone(time: slot.start, coach: @coach)) %>
                  <% if slot.available %>
                    <%= link_to time, nil, class: 'badge badge-pill badge-info',
                                'data-toggle': 'modal', 'data-target': '#confirmAppointmentModal',
                                'data-coach-name': @coach.name,
                                'data-appointment': "#{appointment_confirmation(slot, time, Slot::DURATION_IN_MINUTES)}",
                                'data-slot-id': slot.id
                    %>
                  <% else %>
                    <div class="badge badge-pill badge-secondary"><%= time %></div>
                  <% end %>
                </div>
              <% end %>
            <% end %>

          </td>
        <% end %>
      </tr>
      </tbody>
    </table>
  </div>
</div>

<%= render partial: 'appointment/modal' %>

app/views/home/index.html.erb
<h1 class="h2 text-center">Appointment Scheduler</h1>
<div class="text-center pt-4">
  <%= link_to 'View All Coaches', get_route(@student_id) %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <title>Appointment Scheduler by Chris Dritsas</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <%= stylesheet_link_tag 'application', media: 'all' %>

</head>

<body>

<div class="container-fluid">
  <%= render partial: 'shared/header_nav' %>
</div>

<div class="container">
  <div class="row pt-5">
    <div class="col">
      <%= yield %>
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
<%= javascript_include_tag 'application' %>
<%= yield :javascript %>

</body>
</html>

app/views/shared/_header_nav.html.erb
<div class="row bg-light">
  <div class="col text-center">
    <%= link_to 'Home', root_path, class: 'text-secondary' %>
    <% if session[:student_id] %>
      <span class="text-secondary">|</span>
      <%= link_to 'Logout', student_logout_path, class: 'text-secondary' %>
    <% end %>
  </div>
</div>

app/views/student/_form.html.erb
<%= form_for @student, url: student_create_path, class: 'text-left' do |form| %>
  <% if @student.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(@student.errors.count, "error") %> stopped this account from being created:</h2>
      <ul>
        <% @student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <label for="inputName">Name:</label>
    <%= form.text_field :name, class: 'form-control', id: 'inputName', placeholder: 'Joe Smith' %>
  </div>

  <div class="form-group">
    <label for="time_zone">Select Your Time Zone:</label>
    <%= form.select :time_zone, *[@time_zones], {}, {class: 'form-control'} %>
  </div>
  <button type="submit" class="btn btn-primary btn-block">Continue</button>
<% end %>

app/views/student/new.html.erb
<div class="row">
  <div class="col-12 col-sm-6 offset-sm-3">

    <h1 class="h2 text-center">Create an Account</h1>
    <div class="text-center pt-4">
      <div class="row">
        <div class="col-10 offset-1">
          <div class="alert alert-info">
            You must first create an account to view all coaches.
          </div>
          <div class="pt-3 text-left">
            <%= render partial: 'form' %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/user/logout.html.erb
<h1>User#logout</h1>
<p>Find me in app/views/user/logout.html.erb</p>